# Generated by Django 6.0.4 on 2026-05-12 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cosechero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('cuadrilla', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cosechas.fundo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroKilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variedad', models.CharField(max_length=50)),
                ('kilos', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cosechero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cosechas.cosechero')),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cosechas.fundo')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cosechas.supervisor')),
            ],
        ),
    ]
