# Generated by Django 6.0.4 on 2026-05-12 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cosechas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.AlterModelTable(
            name='cosechero',
            table='cosecheros',
        ),
        migrations.AlterModelTable(
            name='fundo',
            table='fundos',
        ),
        migrations.AlterModelTable(
            name='registrokilo',
            table='registro_kilos',
        ),
        migrations.AlterModelTable(
            name='supervisor',
            table='supervisores',
        ),
    ]
